apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-container
          image: monta2027/my-react:v1  # Updated to Docker Hub image
          imagePullPolicy: Always  # Ensure it pulls from Docker Hub
          ports:
            - containerPort: 3000  # Matches Dockerfile's EXPOSE
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"
